# Generated by Django 4.1.4 on 2022-12-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicinePlants',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=255)),
                ('preview', models.CharField(db_column='preview', max_length=255)),
                ('description', models.CharField(db_column='description', max_length=65535, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
