# Generated by Django 4.1.4 on 2022-12-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_medicineplants_delete_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineplants',
            name='preview',
            field=models.CharField(db_column='preview', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicineplants',
            name='title',
            field=models.CharField(db_column='title', max_length=255, null=True),
        ),
    ]
